
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = ' \x90\x90\r\\.\xcf\xb0\x7fq\xf9\xc0\t\xc2\xe9\x7f'
    
_lr_action_items = {'LPAR':([2,],[7,]),'CONSTANT':([0,3,4,6,7,8,9,14,15,],[2,-3,2,2,10,-2,-4,-5,10,]),'RPAR':([10,11,12,13,16,],[-9,-7,14,-8,-6,]),'COMMA':([10,11,12,13,16,],[-9,-7,15,-8,-6,]),'VARIABLE':([7,15,],[13,13,]),'SPEC':([1,14,],[6,-5,]),'$end':([3,4,5,8,9,14,],[-3,-1,0,-2,-4,-5,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'predicate':([0,4,6,],[1,1,9,]),'argument':([7,15,],[11,16,]),'argument_list':([7,],[12,]),'ontology':([0,],[5,]),'spec':([0,4,],[3,8,]),'spec_list':([0,],[4,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> ontology","S'",1,None,None,None),
  ('ontology -> spec_list','ontology',1,'p_ontology','/localhost/users/gkonstant/Desktop/ssdsat/ontologies.py',43),
  ('spec_list -> spec_list spec','spec_list',2,'p_spec_list','/localhost/users/gkonstant/Desktop/ssdsat/ontologies.py',49),
  ('spec_list -> spec','spec_list',1,'p_preference','/localhost/users/gkonstant/Desktop/ssdsat/ontologies.py',55),
  ('spec -> predicate SPEC predicate','spec',3,'p_literal_list','/localhost/users/gkonstant/Desktop/ssdsat/ontologies.py',61),
  ('predicate -> CONSTANT LPAR argument_list RPAR','predicate',4,'p_predicate','/localhost/users/gkonstant/Desktop/ssdsat/qrp/parsing.py',65),
  ('argument_list -> argument_list COMMA argument','argument_list',3,'p_argument_list','/localhost/users/gkonstant/Desktop/ssdsat/qrp/parsing.py',71),
  ('argument_list -> argument','argument_list',1,'p_single_argument_list','/localhost/users/gkonstant/Desktop/ssdsat/qrp/parsing.py',77),
  ('argument -> VARIABLE','argument',1,'p_argument_variable','/localhost/users/gkonstant/Desktop/ssdsat/qrp/parsing.py',83),
  ('argument -> CONSTANT','argument',1,'p_argument_constant','/localhost/users/gkonstant/Desktop/ssdsat/qrp/parsing.py',89),
]
